"""baseline

Revision ID: 90544b42528d
Revises: 
Create Date: 2026-05-21 23:47:30.889612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90544b42528d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_call_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('success', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('input_summary_length', sa.Integer(), nullable=True),
    sa.Column('output_length', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_prompt_template',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=100), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_template',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_type', sa.String(length=100), nullable=True),
    sa.Column('is_builtin', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('default_calculation_profile', sa.Text(), nullable=True),
    sa.Column('default_warning_rules', sa.Text(), nullable=True),
    sa.Column('default_field_aliases', sa.Text(), nullable=True),
    sa.Column('default_dashboard_config', sa.Text(), nullable=True),
    sa.Column('default_report_config', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('project_type', sa.String(length=100), nullable=True),
    sa.Column('owner_unit', sa.String(length=255), nullable=True),
    sa.Column('supervision_unit', sa.String(length=255), nullable=True),
    sa.Column('construction_unit', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('planned_finish_date', sa.Date(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('default_calculation_profile_id', sa.Integer(), nullable=True),
    sa.Column('default_calculation_method', sa.String(length=100), server_default='auto', nullable=True),
    sa.Column('default_baseline_plan_id', sa.Integer(), nullable=True),
    sa.Column('dashboard_config', sa.Text(), nullable=True),
    sa.Column('report_config', sa.Text(), nullable=True),
    sa.Column('ai_config', sa.Text(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('archive_remark', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['project_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('baseline_plan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('plan_type', sa.String(length=50), server_default='current', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('baseline_date', sa.Date(), nullable=True),
    sa.Column('is_default', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calculation_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('overall_algorithm', sa.String(length=100), server_default='avg_percent', nullable=False),
    sa.Column('group_algorithm', sa.String(length=100), server_default='avg_percent', nullable=False),
    sa.Column('percent_source', sa.String(length=100), server_default='provided_percent_first', nullable=False),
    sa.Column('use_weight', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('weight_field', sa.String(length=100), nullable=True),
    sa.Column('use_value_amount', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('value_field', sa.String(length=100), nullable=True),
    sa.Column('allow_mixed_unit_sum', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('enable_date_plan_calculation', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mapping_template',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_type', sa.String(length=100), nullable=True),
    sa.Column('sheet_name', sa.String(length=255), nullable=True),
    sa.Column('field_structure', sa.Text(), nullable=True),
    sa.Column('is_global', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('use_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progress_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('wbs_code', sa.String(length=100), nullable=True),
    sa.Column('task_code', sa.String(length=100), nullable=True),
    sa.Column('task_name', sa.String(length=500), nullable=True),
    sa.Column('normalized_task_name', sa.String(length=500), nullable=True),
    sa.Column('parent_task_id', sa.Integer(), nullable=True),
    sa.Column('parent_task_name', sa.String(length=500), nullable=True),
    sa.Column('task_level', sa.Integer(), server_default='1', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('area', sa.String(length=255), nullable=True),
    sa.Column('building', sa.String(length=255), nullable=True),
    sa.Column('floor', sa.String(length=255), nullable=True),
    sa.Column('discipline', sa.String(length=255), nullable=True),
    sa.Column('system_name', sa.String(length=255), nullable=True),
    sa.Column('identity_key', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_task_id'], ['progress_task.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('standard_dictionary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('raw_value', sa.String(length=255), nullable=False),
    sa.Column('standard_value', sa.String(length=255), nullable=False),
    sa.Column('is_global', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warning_rule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rule_type', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=50), server_default='warning', nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_batch',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('sheet_name', sa.String(length=255), nullable=True),
    sa.Column('import_group_id', sa.String(length=100), nullable=True),
    sa.Column('import_group_name', sa.String(length=255), nullable=True),
    sa.Column('data_date', sa.Date(), nullable=True),
    sa.Column('header_row_index', sa.Integer(), nullable=True),
    sa.Column('data_start_row_index', sa.Integer(), nullable=True),
    sa.Column('multi_header', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('header_end_row_index', sa.Integer(), nullable=True),
    sa.Column('row_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('imported_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('skipped_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('warning_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('data_quality_score', sa.Float(), nullable=True),
    sa.Column('field_completeness', sa.Float(), nullable=True),
    sa.Column('task_match_rate', sa.Float(), nullable=True),
    sa.Column('valid_row_rate', sa.Float(), nullable=True),
    sa.Column('plan_field_completeness', sa.Float(), nullable=True),
    sa.Column('unit_consistency', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='draft', nullable=False),
    sa.Column('mapping_template_id', sa.Integer(), nullable=True),
    sa.Column('calculation_profile_id', sa.Integer(), nullable=True),
    sa.Column('baseline_plan_id', sa.Integer(), nullable=True),
    sa.Column('batch_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('is_frozen', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('frozen_at', sa.DateTime(), nullable=True),
    sa.Column('freeze_remark', sa.Text(), nullable=True),
    sa.Column('replaced_batch_id', sa.Integer(), nullable=True),
    sa.Column('import_strategy', sa.String(length=50), nullable=True),
    sa.Column('error_report', sa.Text(), nullable=True),
    sa.Column('imported_by', sa.String(length=100), nullable=True),
    sa.Column('confirmed_by', sa.String(length=100), nullable=True),
    sa.Column('published_by', sa.String(length=100), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['baseline_plan_id'], ['baseline_plan.id'], ),
    sa.ForeignKeyConstraint(['calculation_profile_id'], ['calculation_profile.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mapping_field',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('excel_column_name', sa.String(length=255), nullable=False),
    sa.Column('system_field_name', sa.String(length=100), nullable=True),
    sa.Column('field_type', sa.String(length=50), nullable=True),
    sa.Column('is_dimension', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_metric', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_required', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('save_to_extra', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['mapping_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_validation_issue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=True),
    sa.Column('column_name', sa.String(length=255), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progress_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('baseline_plan_id', sa.Integer(), nullable=True),
    sa.Column('identity_key', sa.String(length=500), nullable=True),
    sa.Column('wbs_code', sa.String(length=100), nullable=True),
    sa.Column('task_code', sa.String(length=100), nullable=True),
    sa.Column('task_name', sa.String(length=500), nullable=True),
    sa.Column('parent_task_name', sa.String(length=500), nullable=True),
    sa.Column('area', sa.String(length=255), nullable=True),
    sa.Column('construction_unit', sa.String(length=255), nullable=True),
    sa.Column('building', sa.String(length=255), nullable=True),
    sa.Column('floor', sa.String(length=255), nullable=True),
    sa.Column('discipline', sa.String(length=255), nullable=True),
    sa.Column('system_name', sa.String(length=255), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('total_quantity', sa.Float(), nullable=True),
    sa.Column('planned_quantity', sa.Float(), nullable=True),
    sa.Column('period_quantity', sa.Float(), nullable=True),
    sa.Column('cumulative_quantity', sa.Float(), nullable=True),
    sa.Column('actual_quantity', sa.Float(), nullable=True),
    sa.Column('remaining_quantity', sa.Float(), nullable=True),
    sa.Column('planned_percent', sa.Float(), nullable=True),
    sa.Column('imported_planned_percent', sa.Float(), nullable=True),
    sa.Column('actual_percent', sa.Float(), nullable=True),
    sa.Column('reported_percent', sa.Float(), nullable=True),
    sa.Column('time_planned_percent', sa.Float(), nullable=True),
    sa.Column('progress_deviation', sa.Float(), nullable=True),
    sa.Column('schedule_phase', sa.String(length=50), nullable=True),
    sa.Column('current_period_quantity', sa.Float(), nullable=True),
    sa.Column('current_period_percent', sa.Float(), nullable=True),
    sa.Column('planned_start_date', sa.Date(), nullable=True),
    sa.Column('planned_finish_date', sa.Date(), nullable=True),
    sa.Column('actual_start_date', sa.Date(), nullable=True),
    sa.Column('actual_finish_date', sa.Date(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('value_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('extra_fields', sa.Text(), nullable=True),
    sa.Column('is_manually_edited', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('manual_edit_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['baseline_plan_id'], ['baseline_plan.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['progress_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_import_row',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_export_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('data_date', sa.Date(), nullable=True),
    sa.Column('exported_by', sa.String(length=100), nullable=True),
    sa.Column('exported_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('warning_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['warning_rule.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['progress_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progress_item_edit_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('progress_item_id', sa.Integer(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('edited_by', sa.String(length=100), nullable=True),
    sa.Column('edited_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['progress_item_id'], ['progress_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rectification_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('progress_item_id', sa.Integer(), nullable=True),
    sa.Column('warning_record_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('discipline', sa.String(length=255), nullable=True),
    sa.Column('building', sa.String(length=255), nullable=True),
    sa.Column('floor', sa.String(length=255), nullable=True),
    sa.Column('system_name', sa.String(length=255), nullable=True),
    sa.Column('task_name', sa.String(length=500), nullable=True),
    sa.Column('issue_description', sa.Text(), nullable=True),
    sa.Column('delay_level', sa.String(length=50), nullable=True),
    sa.Column('actual_percent', sa.Float(), nullable=True),
    sa.Column('planned_percent', sa.Float(), nullable=True),
    sa.Column('progress_deviation', sa.Float(), nullable=True),
    sa.Column('responsible_person', sa.String(length=100), nullable=True),
    sa.Column('responsible_unit', sa.String(length=255), nullable=True),
    sa.Column('planned_finish_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='open', nullable=False),
    sa.Column('review_result', sa.Text(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], ),
    sa.ForeignKeyConstraint(['progress_item_id'], ['progress_item.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['warning_record_id'], ['warning_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rectification_action_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rectification_item_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['rectification_item_id'], ['rectification_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rectification_action_log')
    op.drop_table('rectification_item')
    op.drop_table('progress_item_edit_history')
    op.drop_table('warning_record')
    op.drop_table('report_export_record')
    op.drop_table('raw_import_row')
    op.drop_table('progress_item')
    op.drop_table('import_validation_issue')
    op.drop_table('mapping_field')
    op.drop_table('import_batch')
    op.drop_table('warning_rule')
    op.drop_table('standard_dictionary')
    op.drop_table('progress_task')
    op.drop_table('mapping_template')
    op.drop_table('calculation_profile')
    op.drop_table('baseline_plan')
    op.drop_table('audit_log')
    op.drop_table('project')
    op.drop_table('project_template')
    op.drop_table('maintenance_log')
    op.drop_table('ai_prompt_template')
    op.drop_table('ai_call_log')
    # ### end Alembic commands ###
